name: DISEASES
favicon: null
layout_spectrum: 0.22784
typography_spectrum: 0.99237
title: The Diseases
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070d03'
    - '#fcfbfb'
    - '#78842f'
    - '#5b52f1'
    - '#a793f7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5857510350178927
purpose: []
